# Generated by Django 5.2.2 on 2025-06-05 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='coffee_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('image', models.CharField(max_length=2083)),
            ],
            options={
                'verbose_name_plural': 'Coffee Items',
                'ordering': ['name'],
            },
        ),
    ]
